language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  # Cabal
  - ghc: 9.0.1
    env: CABALVER=3.4
  - ghc: 8.10.4
    env: CABALVER=3.2
  - ghc: 8.6.5
    env: CABALVER=2.4
  - ghc: 8.0.2
    env: CABALVER=1.24


  # Stack
  - ghc: 9.0.1
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
  - ghc: 8.10.4
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      ghc --version
      cabal --version
      cabal new-update
      cabal new-build --enable-tests --enable-benchmarks
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh

      # build project with stack
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-test --enable-tests
    else
      stack test --system-ghc
    fi

notifications:
  email: false